// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk2UruhaNPeLRlNDGhe8mqDTQvGT_zggM',
    appId: '1:341824988002:web:431b21333d56818e53c23b',
    messagingSenderId: '341824988002',
    projectId: 'teacherreviews-c487e',
    authDomain: 'teacherreviews-c487e.firebaseapp.com',
    storageBucket: 'teacherreviews-c487e.appspot.com',
    measurementId: 'G-P2DE7GWD7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCnL2smtESkhnpsT3R_3pBUDobSb3h_4o',
    appId: '1:341824988002:android:c1d9b31b26373f2853c23b',
    messagingSenderId: '341824988002',
    projectId: 'teacherreviews-c487e',
    storageBucket: 'teacherreviews-c487e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-sWE5jxMWbUdWTsHaGhYoB8T-0TP7qMQ',
    appId: '1:341824988002:ios:3907089db395911153c23b',
    messagingSenderId: '341824988002',
    projectId: 'teacherreviews-c487e',
    storageBucket: 'teacherreviews-c487e.appspot.com',
    iosBundleId: 'com.example.teacherReview',
  );
}
